blog/urls.py
from django.urls import path, re_path
from blog import views


app_name = 'blog'
urlpatterns = [

    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),   #리스트뷰

    # Example: /blog/post/django-example/     #정규식. 한글도사용할수있게끔.
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),

    # Example: /blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),

    # Example: /blog/archive/2019/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # Example: /blog/archive/2019/nov/
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),  #Month Archive View(MAV)

    # Example: /blog/archive/2019/nov/10/
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),

    # Example: /blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('search/', views.SearchFormView.as_view(), name='search'),
]

bookmark/urls.py
from django.urls import path
from .views import BookmarkLV, BookmarkDV


app_name = 'bookmark'
urlpatterns = [
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', BookmarkDV.as_view(), name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views   #추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),   #각 기능별 폴더에서 해당링크를 만들어관리하겠다.
]

mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #추가
from django.conf import settings #추가 #static(settings~부분활성화.
from .views import HomeView     #추가
from mysite.views import UserCreateView, UserCreateDoneTV   #추가

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register/',UserCreateView.as_view(),name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(),name='register_done'),
    path('', HomeView.as_view(), name='home'),       #추가(메인페이지)
    path('bookmark/', include('bookmark.urls')),  #추가됨, include가있어야 다른 app에 연결가능.
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')), #추가



] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)  #추가, 포토앱.

bookmark/models.py
from django.db import models

# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE',max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark


class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}장고 즐 상세{% endblock %}

{% block content %}

<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Django Bookmark Detail</title>-->
<!--</head>-->
<body>

<div id="content">
    <h1>{{ object.title }}</h1>
    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>

    </ul>
</div>
{% endblock %}
</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}장고 즐 상세{% endblock %}

{% block content %}

<body>

<div id="content">

    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in object_list %}
                 <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>

</body>
</html>
{% endblock %}